### ISSUE TITLE
BUG: asking for password then errors out

### ISSUE THREAD

**Issue by royharoush** [DanMcInerney/autorelay#1]
Hi,
trying to test this in a lab.
installed the requirements, ran based on the readme, gets the following error. 
no idea what password it's asking for.  

```
root@kaliiso:/rtools/tools/autorelay# python autorelay.py -d 192.168.202.166 -x targets.xml
Password: 
Traceback (most recent call last):
  File "autorelay.py", line 240, in <module>
    main(parse_args())
  File "autorelay.py", line 186, in main
    ssh = ssh_client(args.droneip, 22, user, pw)
  File "autorelay.py", line 82, in ssh_client
    client.connect(server, port, user, pw)
  File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 251, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/lib/python2.7/dist-packages/paramiko/util.py", line 278, in retry_on_signal
    return function()
  File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 251, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused

```

**Comment by DanMcInerney** [comment]
Heh, I forgot to make that more explicit. It's asking for the remote
device's password and uses root as the hard coded username. Give me a day
and I'll get that fixed.

**Comment by royharoush** [comment]
kinda conpuzzled here.
isnt this just an automation of responder and metasploit's smb_relay\http_ntlm_rely ? 
at what point would i ssh into a remote machine and run ?  8-|

**Comment by DanMcInerney** [comment]
You're correct, however it automates it on a remote device and network.
Most of my pentesting is done through a jumpbox so I run this script on my
workstation and it does all the work for me on the remote jumpbox then
forwards the snarf web interface to my workstation.

**Comment by DanMcInerney** [comment]
I'll probably write a version of this for use locally in a little bit.

**Comment by royharoush** [comment]
that would be great, though i can live with opening an ssh server on my machine and sshing to myself, just to see how it works. 
you're gonna un-hardcore both the IP and the username, right ? 
edit: nm, i saw that you need to have an ssh tunnel already setup for this to work.

**Comment by DanMcInerney** [comment]
Yeah, I'll need til at least this weekend tho. IP isn't hard coded, should
be an argument to the script

**Comment by DanMcInerney** [comment]
Local version of this script is now at: https://github.com/DanMcInerney/autorelay

Renamed this repo to jumpbox-autorelay. Will combine the scripts and add a --remote option or something later.
